set(_CATKIN_CURRENT_PACKAGE "universal_robot_ros")
set(universal_robot_ros_VERSION "1.0.0")
set(universal_robot_ros_MAINTAINER "Anton Deguet <anton.deguet@jhu.edu>")
set(universal_robot_ros_PACKAGE_FORMAT "1")
set(universal_robot_ros_BUILD_DEPENDS "saw_universal_robot" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(universal_robot_ros_BUILD_EXPORT_DEPENDS "saw_universal_robot" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(universal_robot_ros_BUILDTOOL_DEPENDS "catkin")
set(universal_robot_ros_BUILDTOOL_EXPORT_DEPENDS )
set(universal_robot_ros_EXEC_DEPENDS "saw_universal_robot" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(universal_robot_ros_RUN_DEPENDS "saw_universal_robot" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(universal_robot_ros_TEST_DEPENDS )
set(universal_robot_ros_DOC_DEPENDS )
set(universal_robot_ros_URL_WEBSITE "")
set(universal_robot_ros_URL_BUGTRACKER "")
set(universal_robot_ros_URL_REPOSITORY "")
set(universal_robot_ros_DEPRECATED "")