#
# (C) Copyright 2016-2017 Johns Hopkins University (JHU), All Rights Reserved.
#

# this file is automatically generated by CMake from
# sawUniversalRobotConfig.cmake.in

set (sawUniversalRobot_INCLUDE_DIR "/home/jiameng/catkin_dvrk/src/cisst-saw/sawUniversalRobot/components/include;/home/jiameng/catkin_dvrk/build_release/saw_universal_robot/include")
set (sawUniversalRobot_LIBRARY_DIR "/home/jiameng/catkin_dvrk/devel_release/.private/saw_universal_robot/lib")
set (sawUniversalRobot_LIBRARIES   "sawUniversalRobot")
