set(_CATKIN_CURRENT_PACKAGE "force_dimension_ros")
set(force_dimension_ros_VERSION "1.0.0")
set(force_dimension_ros_MAINTAINER "Anton Deguet <anton.deguet@jhu.edu>")
set(force_dimension_ros_PACKAGE_FORMAT "1")
set(force_dimension_ros_BUILD_DEPENDS "saw_force_dimension_sdk" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(force_dimension_ros_BUILD_EXPORT_DEPENDS "saw_force_dimension_sdk" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(force_dimension_ros_BUILDTOOL_DEPENDS "catkin")
set(force_dimension_ros_BUILDTOOL_EXPORT_DEPENDS )
set(force_dimension_ros_EXEC_DEPENDS "saw_force_dimension_sdk" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(force_dimension_ros_RUN_DEPENDS "saw_force_dimension_sdk" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(force_dimension_ros_TEST_DEPENDS )
set(force_dimension_ros_DOC_DEPENDS )
set(force_dimension_ros_URL_WEBSITE "")
set(force_dimension_ros_URL_BUGTRACKER "")
set(force_dimension_ros_URL_REPOSITORY "")
set(force_dimension_ros_DEPRECATED "")