set(_CATKIN_CURRENT_PACKAGE "dvrk_gazebo")
set(dvrk_gazebo_VERSION "0.0.0")
set(dvrk_gazebo_MAINTAINER "adnan <adnan@todo.todo>")
set(dvrk_gazebo_PACKAGE_FORMAT "1")
set(dvrk_gazebo_BUILD_DEPENDS "gazebo_ros")
set(dvrk_gazebo_BUILD_EXPORT_DEPENDS "gazebo_ros")
set(dvrk_gazebo_BUILDTOOL_DEPENDS "catkin")
set(dvrk_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(dvrk_gazebo_EXEC_DEPENDS "gazebo_ros")
set(dvrk_gazebo_RUN_DEPENDS "gazebo_ros")
set(dvrk_gazebo_TEST_DEPENDS )
set(dvrk_gazebo_DOC_DEPENDS )
set(dvrk_gazebo_URL_WEBSITE "")
set(dvrk_gazebo_URL_BUGTRACKER "")
set(dvrk_gazebo_URL_REPOSITORY "")
set(dvrk_gazebo_DEPRECATED "")